### ISSUE TITLE
Onboarding material is in proprietary data formats

### ISSUE THREAD

**Issue by jeremiah** [OpenChain-Project/Onboarding#2]
I know this may be a bit pedantic but it seems to me that one of the fundamental principles of FOSS is to avoid vendor lock-in. Using Microsoft proprietary formats for sharing data tends to break this principle. Is it possible that there could be other formats provided as well along side docx? Or perhaps we use a semi-proprietary format like PDF if ODF or other open document formats are not possible to use?

**Comment by shanecoughlan** [comment]
Hi @jeremiah ! Just to clarify, OpenXML is an open standard under ECMA-376, ISO/IEC 29500. This is similar to Open Document Format, which is an open standard under ISO/IEC 26300, and Portable Document Format, which is an open standard under ISO 32000-2. 

My understanding is that the issue has tended to be interoperability between contributors and consistent formatting. For the most part our existing community members can read, edit and share OOXML documents with high levels of fidelity regardless of platform (Windows + MS Office, Linux + LibreOffice). A smaller proportion of the community can edit ODF or PDF (everyone can read PDF, but less have the editing tools). This left the route of least resistance to generally create and share via OOXML. Currently we generally make documents available in OOXML and PDF, with @zvr in the Curriculum Team having made great progress in also supporting ODF for the training slides.

We have gradually been pulling away from this in a few directions. One example is that a lot of material is drafted using collaborative tools like Google Docs. Another is that - with our move to GitHub - we are seeing more energy around ideas of using formats such as MarkUp to allow easy editing and document transformation.

Hope this note helps!

**Comment by shanecoughlan** [comment]
I will close this issue unless there are further notes?

**Comment by jeremiah** [comment]
Thanks
